[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
openssh = { version = "0.11.2", features = [ "native-mux" ] }
sha2 = "0.10.8"
tokio = { version = "1.41.0", features = [ "full" ] }
